### ISSUE TITLE
Low FPS issue?

### ISSUE THREAD

**Issue by RSKothari** [stereolabs/zed-python#10]
For some reason, the SDK defaults the camera FPS to 4fps for 720P mode and 2fps for 2K mode. This is despite setting the `camera_fps` flag explicitly. Even if I initialize it without any init parameters, it defaults to a low FPS. What is the reason for this?

**Comment by RSKothari** [comment]
I realized that my drivers for USB 3.0 weren't working correctly. Issue resolved post driver update in Ubuntu.

**Comment by saratrajput** [comment]
@RSKothari Hello. I'm having a similar issue. Could you please tell me the steps to update USB drivers on Ubuntu?
