### ISSUE TITLE
AttributeError: module 'pyzed.camera' has no attribute 'PyCameraInformation'

### ISSUE THREAD

**Issue by chan-e91** [stereolabs/zed-python#17]
Hi, I want to use the calibration parameters fx and fy of the cameras. I tried to get them through PyCameraInformation class. 

import pyzed.camera as zcam
import pyzed.types as tp
def main():
    zed = zcam.PyZEDCamera()
    init_params = zcam.PyInitParameters()
    **cam_params = zcam.PyCameraInformation()**
    init_params.sdk_verbose = False
    err = zed.open(init_params)
    if err != tp.PyERROR_CODE.PySUCCESS:
        exit(1)
    zed_serial = zed.get_camera_information().serial_number
    print("Hello! This is my serial number: {0}".format(zed_serial))
   **print("camera parameters",zed.cam_params.py_calib)**
    zed.close()
if __name__ == "__main__":
    main()

the coded ended with error 
ran hello_zed.py example and the code ended with this error 
**AttributeError: module 'pyzed.camera' has no attribute 'PyCameraInformation'** . can you tell how to access the camera parameters, fx and fy of individual left and right camera.

**Comment by adujardin** [comment]
Hi,
You should try something like this : 
```python
    cam_params = zed.get_camera_information()
    print("Left cam fx: ",cam_params.calibration_parameters.left_cam.fx)
```
Also `PyCameraInformation` is not in pyzed.camera but in pyzed.core (which is not imported here)
