### ISSUE TITLE
Slow Response Time

### ISSUE THREAD

**Issue by Unshure** [stereolabs/zed-python#18]
Hi,
I am currently working on a project that involves using the zed for collision avoidance of an autonomous robot. When I run the example that come with the zed sdk, there is almost no lag in showing the depth image. However when I run the python example for a depth image, there is a noticeable amount of lag between movement and displaying the image. I have the depth mode set to performance, so I am not sure if this is just because running the code in python is slower, or if there is a setting im missing that could improve the response time.

**Comment by adujardin** [comment]
See #16
