### ISSUE TITLE
Can't use with TensorFlow

### ISSUE THREAD

**Issue by adambeytin** [stereolabs/zed-python#21]
I would like to be able to use the ZED camera with the TensorFlow libraries in Python but cannot with zed-python because of version support mismatch.

ZED SDK 2.2.1 only supports CUDA 9, though 2.2.0 supports CUDA 8.
TensorFlow only supports CUDA 8.

zed-python can be built with ZED SDK 2.2.0, but when I try to open a pyzed.camera I get the following error:

> ZED (Init) >> ERROR: Executable was designed for a newer version of the SDK.
EXE v2.2.1 / installed v2.2.0

Is there any solution?

**Comment by orenphysi** [comment]
This issue is critical for me as well, please advise...

**Comment by Alonmeytal** [comment]
+1

**Comment by nesnes** [comment]
> ZED (Init) >> ERROR: Executable was designed for a newer version of the SDK. EXE __v2.2.1__ / installed __v2.2.0__

This error is thrown when a program compiled with a higher version of the SDK is executed with a lower one installed. Just like you are still using the zed-python binaries compiled with the 2.2.1 but with the SDK 2.2.0.

I'll recommend you to clear the current installation of the ZED python wrapper, install the ZED SDK 2.2.0, fresh clone the zed-python repo and follow the compilation and installation instructions.

**Comment by imgntn** [comment]
TF 1.5 now supports CUDA 9 https://github.com/tensorflow/tensorflow/releases

**Comment by adambeytin** [comment]
Thank you very much, removing the zed-python wrapper completely, cloning it again, and recompiling fixed the problem. I had assumed that the cleanall function in setup.py would accomplish the same thing.

That's great news about TF 1.5 supporting CUDA 9! Thank you for the update.
