### ISSUE TITLE
ERROR : Found CUDA 8.0 but the ZED SDK requires 9.0

### ISSUE THREAD

**Issue by dongdonghy** [stereolabs/zed-python#34]
Hi, I want to use ZED with jetpack3.1. I download the ZED_SDK_Linux_JTX2_v2.3.3_JP3.1run file. When I install the run file, I got the following error:
ERROR : Found CUDA 8.0 but the ZED SDK requires 9.0.
It's wired because I download the run file which support Jetpack 3.1 with cuda 8, how could it requires 9.0?

**Comment by adujardin** [comment]
Hi,
Indeed, there was an issue with the Cuda version embedded in the installation script (the installer was actually containing the correct version).
It is now fixed and online.
