### ISSUE TITLE
my zed camera is not detected.

### ISSUE THREAD

**Issue by wataru-sugimoto** [stereolabs/zed-python#42]
Hi,
I'm using ZED camera on windows10 and gtx1060.
Now my camera is not recognized by my PC.
So I tried another PC that has USB3.0, but it didn't recognize the ZED camera too.
I want to know if ZED camera is recognized by PC when it is inserted into USB3.0.

Please can anyone help me with this issue?

**Comment by adujardin** [comment]
Hi,
This is not directly related to the python wrapper.
Try using the Diagnostic Tool and contact the support (support@stereolabs.com) if the problem persists.
