### ISSUE TITLE
cl.exe not found

### ISSUE THREAD

**Issue by rukie** [stereolabs/zed-python#44]
When attempting to install within an Anaconda environment, the script errored out because it could not find cl.exe

I addressed this by:
1) Launch Anaconda Prompt with administrator privleges
2) Execute C:\Program Files (x86)\Microsoft Visual Studio 14.0\VC\bin\amd64\vcvars64.bat

Leaving this in case anyone else comes across similar issues

**Comment by icicle4** [comment]
install vs2015 and ensure c++ module  installed.
