### ISSUE TITLE
Recorded SVO random access

### ISSUE THREAD

**Issue by ajdroid** [stereolabs/zed-python#46]
Hi, is there a way to access images in the SVO randomly? This is a common use case if I am using a recorded SVO interactively in Jupyter or Ipython.

My current way is to run `cam.grab()` repeatedly (the required number of times) to move forward and re-load the camera object if I must move back. 

Best,
Abhijat

**Comment by obraun-sl** [comment]
Hi,
You can use cam.set_svo_position( ) with a random number between 0 and get_svo_number_of_frames(). Only one grab then is enough to get all the data at that specific position.

**Comment by ajdroid** [comment]
Thanks!
