### ISSUE TITLE
ImportError: DLL load failed: The specified module could not be found.

### ISSUE THREAD

**Issue by JonesParking18** [stereolabs/zed-python#55]
I could run setup.py without any problem. I can even import pyzed. But I cannot import pyzed.camera (nor other pyzed.* modules) because of 
` File "<stdin>", line 1, in <module>
ImportError: DLL load failed: The specified module could not be found.`
error. I looks like it is a problem with a path. Does anyone know how to fix this?
I am running this on Windows10 with Anaconda, python 3.5.6. Let me know if you need more information.

**Comment by linthy** [comment]
Hello, do you solve this issues?
I meet the same problem today.
I am running this on Windows10 with Anaconda, python 3.5.5.

**Comment by hmc-cs-syasunaga** [comment]
Hi. It seems like the problem was with the installation of the CUDA toolkit. 
I deleted all of the installed CUDA-related softwares and installed it again and it worked!
