### ISSUE TITLE
Running ZED camera with CUDA 9.1 and ZED SDK 2.4, but got some error message

### ISSUE THREAD

**Issue by vb123er951** [stereolabs/zed-python#59]
The README said this is for ZED SDK 2.3, can it run with SDK 2.4?
My computer is using CUDA 9.1 and Cudnn 7.1.3, and I installed ZED SDK 2.4 version, otherwise the camera can't work.

When I running the program in tutorial directory, it output this message:
```
ZED (Init) >> ERROR: Executable was designed for SDK v2.3.3 / installed v2.4.1

ZED (Init) >> Video mode: HD720@60
```

**Comment by vb123er951** [comment]
Hi, I tried to re-compile/ re-install the packages, I use the commands below:
```
python3 setup.py build
python3 setup.py install
```
it doesn't have error messages, but after install I used the command
`python3 -c "import pyzed.camera as zcam`
it shows ImportError: no module named 'pyzed.camera'

Did I miss something?

**Comment by adujardin** [comment]
Did you install it with enough permission?
e.g. `sudo python3 setup.py install`

**Comment by vb123er951** [comment]
Yes, I did.

**Comment by vb123er951** [comment]
I have checked the python packages, the packages have been installed.
And I tried to import command again, it imported successfully, but I don't know why suddenly works well.
Anyway, thank you for the assistance!
